import Hero from "@/components/Hero/Hero";
import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AirLearning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-[90px] dark:bg-slate-900">
        <header>
          <Navbar />
          <Hero />
        </header>
      </main>
    </>
  );
}
