import ContactUs from "@/components/ContactUs/ContactUs";
import EmailSubmit from "@/components/EmailSubmit/EmailSubmit";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import PricingPlans from "@/components/PricingPlans/PricingPlans";
import Reviews from "@/components/Reviews/Reviews";
import ServiceFeatures from "@/components/ServiceFeatures/ServiceFeatures";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AirLearning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-[90px]">
        <Header />
        <ServiceFeatures />
        <Reviews />
        <EmailSubmit />
        <PricingPlans />
        <ContactUs />
        <Footer />
      </main>
    </>
  );
}
