import Featured from "@/components/Featured/Featured";
import Footer from "@/components/Footer/Footer";
import Hero from "@/components/Hero/Hero";
import Navbar from "@/components/Navbar/Navbar";
import PostsCollection from "@/components/PostsCollection/PostsCollection";
import RecentPosts from "@/components/RecentPosts/RecentPosts";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AirBlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-[40px] dark:bg-slate-900">
        <Navbar className="sticky" />
        <header>
          <Hero />
        </header>
        <Featured />
        <PostsCollection />
        <RecentPosts />
        <Footer />
      </main>
    </>
  );
}
